title: Justin Yu
description: CS Undergrad @ Rutgers 
site_title: 'Justin Yu'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: justinyugit
blog_url: 
email: justin.yu1@rutgers.edu
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: 

# Google Analytics ID
google_analytics: 